/**
 * One module, `dist/plugin.js`, committed, and named by the root
 * `package.json`'s `exports` as `bc-canvas-editor/remark`.
 *
 * Committed for the reason `cli/build.js` spells out at length (ticket 051
 * decisions 3 and 4): npm 11 gates `prepare` behind `allow-scripts` and npm 10
 * drags the whole devDep tree through it, so an install-time build is
 * version-dependently broken. A site's `npm i github:mitchellvanw/…` copies
 * bytes and runs nothing.
 *
 * Nothing is external. A remark plugin runs inside somebody else's build, and
 * the one thing that build must not have to know about is our dependency tree
 * — so the renderer is inlined from `src/lib/render/dist/render.js` exactly as
 * the CLI inlines it, never re-derived from `CanvasSheet.svelte`. That is what
 * keeps "the sheet a fence draws and the sheet the editor exports are the same
 * sheet" structural. It costs a third committed copy of the ~200 KB of base64
 * fonts, which is the price ticket 051 decision 5 already weighed and paid.
 *
 * The rebuild order is `render` then `cli` then `remark`, which
 * `npm run build:bundles` spells out and three staleness tests catch either
 * way — `plugin.test.ts` builds to a scratch path (the optional argument) and
 * diffs against the committed bytes.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { build } from 'esbuild';
import { fontFaceCss, renderSheetParts } from '../src/lib/render/dist/render.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const outfile = path.resolve(process.argv[2] ?? path.join(here, 'dist/plugin.js'));

/**
 * `dist/sheet.css` — the same preamble the plugin inlines, as a file a site can
 * import instead (`{ css: 'imported' }`).
 *
 * It exists because React's server render escapes the text inside a `<style>`
 * element, which turns every quoted font name, attribute selector and child
 * combinator in the sheet's CSS into `&#x27;`, `&quot;` and `&gt;` — measured
 * on a real Docusaurus build, where the sheet came out in Times. A stylesheet
 * goes through the site's own CSS pipeline and never through React.
 *
 * Written from the renderer rather than kept beside it: it is `fontFaceCss()`
 * and `renderSheetParts()`'s own bytes, so it cannot describe a sheet that is
 * no longer the one being drawn. Which canvas draws it does not matter — the
 * CSS is identical whatever the content, which `src/lib/fence/fence.test.ts`
 * pins — and a committed example is used rather than a blank literal here so
 * that a schema change reaches this file through the same migration and
 * pinning test as everything else.
 */
function stylesheet() {
	const example = JSON.parse(
		readFileSync(path.join(here, '../examples/order-fulfillment.bcc.json'), 'utf8')
	);
	return (
		`/* The bcc fence's sheet — generated by remark/build.js, do not edit. */\n` +
		`${fontFaceCss()}\n${renderSheetParts(example).css}\n`
	);
}

writeFileSync(path.join(path.dirname(outfile), 'sheet.css'), stylesheet());

await build({
	absWorkingDir: here,
	entryPoints: ['src/plugin.ts'],
	outfile,
	bundle: true,
	platform: 'node',
	target: 'node20',
	format: 'esm',
	sourcemap: false,
	tsconfig: path.join(here, 'tsconfig.json'),
	logLevel: 'warning'
});
